In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df_ex = pd.read_csv('export_by_state_and_year_CA.csv', low_memory=False)
df_im = pd.read_csv('import_by_state_and_year_CA.csv', low_memory=False)

In [3]:
states = ['AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA','WA', 'WV', 'WI', 'WY']

In [4]:
df_total = df_ex.add(df_im, fill_value=0)

In [5]:
df_total.drop("2007", axis=1, inplace=True)
df_total.drop("2008", axis=1, inplace=True)
df_total.drop("2010", axis=1, inplace=True)
df_total.drop("2011", axis=1, inplace=True)
df_total.drop("2012", axis=1, inplace=True)
df_total["state"] = states
df_total

,state,2013,2014,2015,2016,2017,2018
0,AL,6331458882,6465835531,6105157222,6187295126,6761875896,7186252446
1,AK,1151652042,1159294028,1029541168,963670528,1161411155,1164642848
2,AS,0,0,0,0,0,0
3,AZ,3788978076,3754250567,3720162263,3394373553,3510733109,3690044224
4,AR,2579223755,2331528472,2003428169,1914783988,2046460376,2105849391
5,CA,45262019389,46128588360,44782904179,43964080863,45494625407,44848264867
6,CO,6097223143,5991982701,4610564037,4094144609,5030270574,5362730745
7,CT,5683309359,5397765719,5069514186,4534969669,4768212339,5538807400
8,DE,2205116602,2463787090,1360602565,980740437,1465789899,2054701254
9,DC,146450666,62558365,65334867,77276494,103252097,94566715
10,FL,9656100523,8094712961,8074065606,7754769890,7981134480,8583825965
11,GA,10441912505,11503814763,10609401873,9835029326,10416851755,10805931595
12,HI,160482030,282409494,295091164,300710482,157349012,147170914
13,ID,2622921307,2284991595,1891443101,1936916818,1903120365,2051149885
14,IL,60109095343,67085796462,47166067589,41179589568,49727316266,55691886655
15,IN,19606233137,20338289863,18819408185,18756762028,21057778434,21368851456
16,IA,7808452932,7917729057,6630588702,5810389945,6701395909,6967090115
17,KS,4315428563,4228651735,3966829598,3403660977,4037742058,3666608636
18,KY,11787587077,11670736198,10922476702,10913983815,11254633057,11833377939
19,LA,5057196637,5381486810,4361080723,4162906040,4868401624,6827053370
20,ME,3567272858,3562586745,3206548041,3050746367,2973618937,3306797717
21,MD,3915759532,3978078825,3525162324,3304103739,3494555233,3752311129
22,MA,12413787903,11960792004,10727422623,10283658061,9761373939,10295228944
23,MI,74870402387,74248874472,69058807773,71754472801,72280508539,71279506360
24,MN,19181040072,19345952381,13102610881,11537726644,13900883205,14372053842
25,MS,3169356925,3155513992,3120797986,3088308680,3139140310,3174520026
26,MO,8033161508,8025847449,7885097101,8175233698,8397822277,9778763529
27,MT,5813346796,6104555231,4015122692,3501625477,4316944073,4676730960
28,NE,3184447184,3335302601,2410511781,1939571256,2407423243,2660624499
29,NV,1963915379,2047799391,2057389631,2284204089,2008046296,2118571138
30,NH,9213083671,7707079363,5442666308,4827023765,6031818184,6305448530
31,NJ,15861682516,16737102104,14361773946,13670048989,14536489521,15463200700
32,NM,531131435,420350057,377651951,395798956,329702424,435239213
33,NY,36259851805,34167641319,30412710533,30262100690,29578951416,30713120000
34,NC,10174222288,10192692508,10284344815,9686628996,9928575701,10261313579
35,ND,5158919730,6715849817,4652177169,4609743501,5940729243,7971742235
36,OH,37372309193,37784751617,33912706959,30600845781,31060816857,33303244352
37,OK,7826797301,8318844495,6008556081,3942225940,4441446431,5945127976
38,OR,6020778362,5842017287,5263804607,4635884280,5091602292,6250288214
39,PA,23227070092,24706561380,22301835356,19942326103,21937947284,22546214970
40,RI,866074085,891207003,950855797,932643933,1075354853,1135957494
41,SC,6208813159,6446504068,6441438032,6412185805,6595653003,6929165097
42,SD,1156019024,1195763625,1070293161,816352739,950002343,1009144882
43,TN,14140422850,14594614532,14406352893,13841661322,13518798049,13070378770
44,TX,40741227053,48550789386,41310772622,35100866745,41053805192,47647573994
45,UT,2977846305,3098861212,3308705428,3321650329,3402351055,3700427276
46,VT,5644336811,5309003350,4044318040,3770993231,3444942094,3525045445
47,VA,5065036423,5523284769,5182309695,4795537822,4980057160,5389873217
48,WA,23564640933,25264442019,21548485366,19791402387,21503508287,22649752681
49,WV,3289994568,3317390013,2899365109,2643039916,2791561715,2664613902
50,WI,11740813926,12458334010,11516887491,10673395111,11142405742,11833176898
51,WY,2260524417,2365926494,1006347180,727049411,791513550,964622588

In [6]:
df_total.to_csv("./trade_values_by_state_and_year_CA.csv", sep=',',index=False)